article/urls.py
# 引入path
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # 参数article/分配了app的访问路径；
    # include将路径分发给下一步处理；
    # namespace可以保证反查到唯一的url，即使不同的app使用了相同的url（后面会用到）。

    # 新增代码，配置app的url
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 注册用户表单
# 对数据库进行操作的表单应该继承forms.ModelForm，可以自动生成模型中已有的字段
class UserRegisterForm(forms.ModelForm):
    # 复写User的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致，请重试。")

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from .forms import UserLoginForm, UserRegisterForm
from django.contrib.auth.models import User
# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required

# Create your views here.

def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)
                return redirect("article:article_list")
            else:
                return HttpResponse("账号或密码输入有误。请重新输入~")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = { 'form': user_login_form }
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

# 用户退出
def user_logout(request):
    logout(request)
    return redirect("article:article_list")

# 用户注册
def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect("article:article_list")
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = { 'form': user_register_form }
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        # 验证登录用户、待删除用户是否相同
        if request.user == user:
            # 退出登录，删除数据并返回博客列表
            logout(request)
            user.delete()
            return redirect("article:article_list")
        else:
            return HttpResponse("你没有删除操作的权限")
    else:
        return HttpResponse("仅接受POST请求")

templates/userprofile/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %} {% load static %}
    {% block title %} 登录 {% endblock title %}
    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <br>
                    <h5>还没有账号？</h5>
                    <h5>点击<a href="{% url "userprofile:register" %}">注册账号</a>加入我们吧！</h5>
                    <form method="post" action=".">
                        {% csrf_token %}
                        <!-- 账号 -->
                        <div class="form-group">
                            <label for="username">账号</label>
                            <input type="text" class="form-control" id="username" name="username">
                        </div>
                        <!-- 密码 -->
                        <div class="form-group">
                            <label for="password">密码</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary">提交</button>
                    </form>
                    <br>
                    <h5>忘记密码了？</h5>
                    <h5>点击<a href='{% url "password_reset_recover" %}'>这里</a>重置密码</h5>
                </div>
            </div>
        </div>
    {% endblock content %}
</body>
</html>

templates/userprofile/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    {% extends "base.html" %} {% load static %}
    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <br>
                    <form method="post" action=".">
                        {% csrf_token %}
                        <!-- 账号 -->
                        <div class="form-group col-md-4">
                            <label for="username">昵称</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <!-- 邮箱 -->
                        <div class="form-group col-md-4">
                            <label for="email">Email</label>
                            <input type="text" class="form-control" id="email" name="email">
                        </div>
                        <!-- 密码 -->
                        <div class="form-group col-md-4">
                            <label for="password">设置密码</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <!-- 确认密码 -->
                        <div class="form-group col-md-4">
                            <label for="password2">确认密码</label>
                            <input type="password" class="form-control" id="password2" name="password2" required>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary">提交</button>
                    </form>
                </div>
            </div>
        </div>
    {% endblock content %}
</body>
</html>