article/urls.py
# 引入path
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # 参数article/分配了app的访问路径；
    # include将路径分发给下一步处理；
    # namespace可以保证反查到唯一的url，即使不同的app使用了相同的url（后面会用到）。

    # 新增代码，配置app的url
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

templates/base.html
{#<!--#}
{#    载入静态文件#}
{#    使用 Django 3 学习的读者改为 {% load static %}#}
{#-->#}
{% load static %}
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="en">
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="UTF-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>
<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.6.3.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- 引入layer.js -->
    <script src="{% static 'layer/layer.js' %}"></script>
{#    <script src="../static/layer/mobile/layer.js"></script>#}
</body>
</html>

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load static %}
    <div>
        <br><br><br>
    </div>
    <footer class="py-3 bg-dark fixed-bottom">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; KwokFu-Study 2023</p>
        </div>
    </footer>

</body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">我的博客</a>

            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                    </li>
                    <!-- Django的 if 模板语句 -->
                    {% if user.is_authenticated %}
                        <!-- 如果用户已经登录，则显示用户名下拉框 -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                                <a class="dropdown-item" href="{% url "userprofile:logout" %}">退出登录</a>
                            </div>
                        </li>
                        <!-- 如果用户未登录，则显示 “登录” -->
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                        </li>
                        <!-- if 语句在这里结束 -->
                    {% endif %}

                    {% if user.is_authenticated %}
                        <form
                                style="display:none;"
                                id="user_delete"
                                action="{% url 'userprofile:delete' user.id %}"
                                method="POST"
                        >
                            {% csrf_token %}
                            <button type="submit">发送</button>
                        </form>
                        <script>
                            function user_delete() {
                                // 调用layer弹窗组件
                                layer.open({
                                    title: "确认删除",
                                    content: "确认删除用户资料吗？",
                                    yes: function(index, layero) {
                                        $('form#user_delete button').click();
                                        layer.close(index);
                                    },
                                })
                            }
                        </script>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</body>
</html>