article/urls.py
# 引入path
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # 参数article/分配了app的访问路径；
    # include将路径分发给下一步处理；
    # namespace可以保证反查到唯一的url，即使不同的app使用了相同的url（后面会用到）。

    # 新增代码，配置app的url
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
]

article/models.py
# 导入内建的User模型
from django.contrib.auth.models import User
from django.db import models
# timezone 用于处理时间相关事务
from django.utils import timezone


# Create your models here.
# 每当你修改了models.py文件，都需要用makemigrations和migrate这两条指令迁移数据。
# python manage.py makemigrations
# python manage.py migrate
# 在迁移之后，Model的编写就算完成了

# 博客文章数据模型
class ArticlePost(models.Model):
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)
    # 文章正文，保存大量文本使用TextField
    body = models.TextField()
    # 文章创建时间，参数default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)
    # 文章更新时间，参数auto_now=True指向每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)

    # 内部类 class Meta 用于给 model 定义元数据
    # 这不是字段，是为了规范类的行为
    # 表明了每当我需要取出文章列表，作为博客首页时，按照-created（即文章创建时间，负号标识倒序）来排列，
    # 保证了最新文章永远在最顶部位置
    class Meta:
        ordering = ('-created',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        return self.title


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlePost

# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body')

article/views.py
import markdown
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ArticlePost
from .forms import ArticlePostForm
from django.contrib.auth.models import User


# Create your views here.

def article_list(request):
    # 取出所有博客文章
    articles = ArticlePost.objects.all()
    # 需要传递给模板（templa）的对象
    context = {'articles': articles}

    # render函数：载入模板，并返回context对象
    # request是固定的request对象，照着写就可以
    # article/list.html定义了模板文件的位置、名称
    # context定义了需要传入模板文件的上下文
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)
    # 将markdown语法渲染成html样式
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         # 包含 缩写、表格等常用扩展
                                         'markdown.extensions.extra',
                                         # 语法高亮扩展
                                         'markdown.extensions.codehilite',
                                     ])
    # 需要传递给模板的对象
    context = {'article': article}
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)

def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_article.author = User.objects.get(id=1)
            # 将新文章保存到数据库中
            new_article.save()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文
        context = {'article_post_form': article_post_form}
        # 返回模板
        return render(request, 'article/create.html', context)

def article_delete(request, id):
    # 根据id获取需要删除的邮件
    article = ArticlePost.objects.get(id=id)
    article.delete()
    return redirect("article:article_list")

def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")

def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    # 将提交的数据赋值到表单实例中
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        article_post_form = ArticlePostForm()
        context = {'article': article, 'article_post_form': article_post_form}
        return render(request, 'article/update.html', context)

templates/article/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %}{% load static %}
    {% block title %} 写文章 {% endblock title %}
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock content %}
</body>
</html>

templates/article/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %}
    {% load static %}

    {% block title %}
        文章详情
    {% endblock title %}

    {% block content %}
        <div class="container">
            <div class="row">
                <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
                <div class="col-12 alert-success">作者：{{ article.author }}
{#                <a href="#" onclick="confirm_delete()">删除文章</a>#}
                    · <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                    · <a href="{% url "article:article_update" article.id %}">编辑文章</a>
                    <form
                        style="display: none"
                        id="safe_delete"
                        action="{% url 'article:article_safe_delete' article.id %}"
                        method="post">
                        {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>
                </div>
                <div class="col-12">
                    <p>{{ article.body|safe }}</p>
                </div>
            </div>
        </div>
{#        <script>#}
{#            // 删除文章的函数#}
{#            function confirm_delete() {#}
{#                // 调用layer弹窗组件#}
{#                console.log("hello")#}
{#                layer.open({#}
{#                    // 弹窗标题#}
{#                    title: "确认删除",#}
{#                    // 正文#}
{#                    content: "确认删除这篇文章吗？",#}
{#                    // 点击确定按钮后调用的回调函数#}
{#                    btn: ['确定', '取消'],#}
{#                    yes: function(index, layero) {#}
{#                        // 指定应当前往的 url#}
{#                        location.href='{% url "article:article_delete" article.id %}'#}
{#                    },#}
{#                })#}
{#            }#}
{#        </script>#}
        <script>
            function confirm_safe_delete() {
                layer.open({
                    title: "确认删除",
                    content: "确认删除这篇文章吗",
                    yes: function (index, layero) {
                        $('form#safe_delete button').click();
                        layer.close(index);
                    },
                })
                console.log("hell")
            }
        </script>
    {% endblock content %}
</body>
</html>

templates/article/index.html
<body>
<h1>hello</h1>
</body>

templates/article/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <!-- extends表明此页面继承自 base.html 文件 -->
    {% extends "base.html" %}
    {% load static %}

    <!-- 写入base.html 中定义的title -->
    {% block title %}
        首页
    {% endblock title %}

    <!-- 写入content -->
    {% block content %}
        <!-- 定义放置文章标题的div容器 -->
        <div class="container">
            <div class="row mt-2">
                {% for article in articles %}
                    <!-- 文章内容 -->
                    <div class="col-4 mb-4">
                        <!-- 卡片容器 -->
                        <div class="card h-100">
                            <!-- 标题 -->
                            <h4 class="card-header">{{ article.title }}</h4>
                            <!-- 摘要 -->
                            <div class="card-body">
                                <p class="card-text">{{ article.body|slice:'100' }}...</p>
                            </div>
                            <!-- 注脚 -->
                            <div class="card-footer">
                                <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    {% endblock content %}



</body>
</html>

templates/article/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %} {% load static %}
    {% block title %} 更新文章 {% endblock title %}
    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <br>
                    <form method="post" action=".">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="title">文章标题</label>
                            <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                            <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                        </div>
                        <div class="form-group">
                            <label for="body">文章正文</label>
                            <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                            <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">完成</button>
                    </form>
                </div>
            </div>
        </div>
    {% endblock content %}
</body>
</html>